; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[common]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_compat_mode = strict
lib_ldf_mode = chain
board_build.filesystem = spiffs
board_build.partitions = default.csv
lib_deps = 
	esp32async/AsyncTCP@^3.4.9
	esp32async/ESPAsyncWebServer@^3.9.1
	vshymanskyy/Preferences@^2.2.2
	miguelbalboa/MFRC522@^1.4.12
	bbx10/DNSServer@^1.1.0
	olikraus/U8g2@^2.36.15
	dfrobot/DFRobotDFPlayerMini@^1.0.6
	plerup/EspSoftwareSerial@^8.2.0
	robtillaart/I2CKeyPad@^0.5.1
build_flags = 
	-D CONFIG_ASYNC_TCP_MAX_ACK_TIME=5000
	-D CONFIG_ASYNC_TCP_PRIORITY=10
	-D CONFIG_ASYNC_TCP_QUEUE_SIZE=64
	-D CONFIG_ASYNC_TCP_RUNNING_CORE=1
	-D CONFIG_ASYNC_TCP_STACK_SIZE=4096
extra_scripts = pre:upload-spiffs.py
monitor_raw = yes

[env:esp32dev]
extends = common
lib_deps = 
	esp32async/AsyncTCP@^3.4.9
	esp32async/ESPAsyncWebServer@^3.9.1
	vshymanskyy/Preferences@^2.2.2
	miguelbalboa/MFRC522@^1.4.12
	bbx10/DNSServer@^1.1.0
	olikraus/U8g2@^2.36.15
	dfrobot/DFRobotDFPlayerMini@^1.0.6
	plerup/EspSoftwareSerial@^8.2.0
	robtillaart/I2CKeyPad@^0.5.1

[env:esp32dev_debug]
extends = common
build_flags = 
	${common.build_flags}
	-D DEBUG_BUILD
lib_deps = 
	esp32async/AsyncTCP@^3.4.9
	esp32async/ESPAsyncWebServer@^3.9.1
	vshymanskyy/Preferences@^2.2.2
	miguelbalboa/MFRC522@^1.4.12
	bbx10/DNSServer@^1.1.0
	olikraus/U8g2@^2.36.15
	dfrobot/DFRobotDFPlayerMini@^1.0.6
	plerup/EspSoftwareSerial@^8.2.0
	robtillaart/I2CKeyPad@^0.5.1
